require: rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - define
    - describe
    - draw
    - factory
    - group
    - guard
    - namespace
    - trait
    - aasm

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - spec/dummy/**/*
