openstack:
  service: OpenStack
  container: <%= ENV['OPENSTACK_CONTAINER'] %>
  auth_url: <%= ENV['OPENSTACK_AUTH_URL'] %>
  region: <%= ENV['OPENSTACK_REGION'] %>
  credentials:
    username: <%= ENV['OPENSTACK_USERNAME'] %>
    api_key: <%= ENV['OPENSTACK_API_KEY'] %>
    temp_url_key: <%= ENV['OPENSTACK_TEMP_URL_KEY'] %>
