openstack:
  service: OpenStack
  container: <%= Rails.application.config.x.openstack.fetch(:container) %>
  authentication_url: <%= Rails.application.config.x.openstack.fetch(:authentication_url) %>
  region: <%= Rails.application.config.x.openstack.fetch(:region) %>
  credentials:
    username: <%= Rails.application.credentials.openstack.fetch(:username) %>
    api_key: <%= Rails.application.credentials.openstack.fetch(:api_key) %>
    temporary_url_key: <%= Rails.application.credentials.openstack.fetch(:temporary_url_key) %>
